# Generated by Django 6.0.2 on 2026-03-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_debtpayment_debtrecurringpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DebtRecurringPayment',
        ),
        migrations.DeleteModel(
            name='DebtPayment',
        ),
        migrations.DeleteModel(
            name='Debt',
        ),
    ]
